name = "rankpublic-consumer-jobs"
main = "src/index.ts"
compatibility_date = "2024-10-31"

[vars]
GATEWAY_BASE_URL = "https://api.rankpublic.com"
MAX_JOBS_PER_TICK = "10"


[triggers]
crons = ["* * * * *"]
